name: R Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Go to path
        run: cd stat1201
        
      - name: Set up R 4.1.2
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.2
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools
          working-directory: 'stat1201'
       
        
      - name: Run tests
        run: |
          library(devtools)
          devtools::test()
        shell: Rscript {0}
